version = 0.1

[default.deploy.parameters]
stack_name = "express-trang"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
disable_rollback = false
s3_prefix = "express-trang"
image_repositories = []

[default.global.parameters]
region = "us-west-2"
